# Generated by Django 2.2.1 on 2019-05-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hose', '0002_auto_20190521_0016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hosehistory',
            unique_together={('date', 'event', 'hose')},
        ),
    ]
