# Generated by Django 2.2.1 on 2019-05-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hose', '0004_auto_20190521_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoseevent',
            name='status',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
